services:
  backend:
    build:
      context: .
    container_name: lassen-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./users.db:/app/users.db
    restart: always