services:
  backend:
    build:
      context: .
    container_name: lassen-backend
    ports:
      - "7070:7070"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./users.db:/app/users.db
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always