name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.EC2_KNOWN_HOST }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2 via SSH
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/lassen/backend
            git pull origin main
            docker compose down
            docker compose up --build -d
          EOF